In [1]:
import numpy as np
import pandas as pd
d = {'x': [1, 2, 3], 'y': [2, 4, 8], 'z': 100}
pd.DataFrame(d)

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100

In [2]:
pd.DataFrame(d, index=[100, 200, 300], columns=['z', 'y', 'x'])

       z  y  x
100  100  2  1
200  100  4  2
300  100  8  3

In [3]:
import pandas as pd

student_dict = {
    'Name': ['Joe', 'Nat', 'Harry'],
    'Age': [20, 21, 19],
    'Marks': [85.10, 77.80, 91.54]
}

In [4]:
student_df = pd.DataFrame(student_dict)
print(student_df)

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

In [5]:
student_df = student_df.set_index('Name')
print(student_df)

       Age  Marks
Name
Joe     20  85.10
Nat     21  77.80
Harry   19  91.54

In [6]:
import pandas as pd

data = {
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1200, 300, 800],
    'Quantity': [50, 150, 100]
}
df = pd.DataFrame(data)
print(df)

  Product  Price  Quantity
0  Laptop   1200        50
1  Tablet    300       150
2   Phone    800       100

In [7]:
df.index = pd.RangeIndex(start=1, stop=4, step=1)

print(df)

  Product  Price  Quantity
1  Laptop   1200        50
2  Tablet    300       150
3   Phone    800       100

In [8]:
import pandas as pd
patientID = [101,23,48,49]
name =       ['alice','bob','charlie','Eric']
date_of_birth = ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']

myDF = pd.DataFrame(zip(patientID, name,date_of_birth), columns=['patientID', 'name', 'date_of_birth'])
myDF

   patientID     name          date_of_birth
0        101    alice             2023-01-01
1         23      bob             2023-01-02
2         48  charlie       3/10/2020 143045
3         49     Eric  13th of October, 2023

In [9]:
stocks = ["IBM", "APPLE", "TWTTR", "GE", "MSFT"]
prices = [115.00, 119.14, 19.77, 25.99, 26]

pd.DataFrame(zip(stocks, prices), columns=['stocks', 'prices'])

  stocks  prices
0    IBM  115.00
1  APPLE  119.14
2  TWTTR   19.77
3     GE   25.99
4   MSFT   26.00

In [10]:
import pandas as pd
data = [{'x': 1, 'y': 2, 'z': 100},
     {'x': 2, 'y': 4, 'z': 100},
     {'x': 3, 'y': 8, 'z': 100}]

pd.DataFrame(data)

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100

In [11]:
l = [[1, 2, 100],
     [2, 4, 100],
     [3, 8, 100]]

pd.DataFrame(l, columns=['x', 'y', 'z'])

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100

In [12]:
arr = np.array([[1, 2, 100],[2, 4, 100],[3, 8, 100]])
df = pd.DataFrame(arr, columns=['x', 'y', 'z'])
df

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100

In [13]:
arr[0, 0] = 1000
df

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100