In [1]:
import numpy as np
import pandas as pd 

d = {'x' : [1, 2, 3], 'y' : [2,4,8], 'z' :100}
df = pd.DataFrame(d)
df.head()

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100

In [2]:
df2 = pd.DataFrame(d, index=[100, 200, 300], columns=['z', 'y', 'x'])

df2.head()

       z  y  x
100  100  2  1
200  100  4  2
300  100  8  3

In [3]:
student_dict = {'name': ['Joe', 'Nat', 'Henry'], 'age': [20, 21, 19], 'grade': ['A', 'B', 'C']}
student_df = pd.DataFrame(student_dict)
student_df.head()

    name  age grade
0    Joe   20     A
1    Nat   21     B
2  Henry   19     C

In [4]:
student_df = student_df.set_index('name')
student_df.head()
print(student_df.head())

       age grade
name
Joe     20     A
Nat     21     B
Henry   19     C

In [5]:
data = {'Product' : ['Laptop', 'Tablet', 'Smartphone'], 'Price' : [1200, 300, 800], 'Quantity' : [10, 20, 15]}
df3 = pd.DataFrame(data)
df3.head()

      Product  Price  Quantity
0      Laptop   1200        10
1      Tablet    300        20
2  Smartphone    800        15

In [6]:
df3.index = pd.RangeIndex(start=1, stop=4, step=1)
df3.head()

      Product  Price  Quantity
1      Laptop   1200        10
2      Tablet    300        20
3  Smartphone    800        15

In [ ]:
patient_ID = [101, 102, 103]
name = ['Alice', 'Bob', 'Charlie']
date_of_birth = ['1990-01-01', '1985-06-15', '1992-03-22']

employee_df = pd.DataFrame(zip(patient_ID, name, date_of_birth), columns=['Patient ID', 'Name', 'Date of Birth'])
employee_df

   Patient ID     Name Date of Birth
0         101    Alice    1990-01-01
1         102      Bob    1985-06-15
2         103  Charlie    1992-03-22

:

In [1]:
data = {
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1200, 300, 800],
    'Quantity': [50, 150, 100]
}
df3 = pd.DataFrame(data)

df3.head()

NameError: name 'pd' is not defined